#!/usr/bin/bash
# Select screen area and take a screenshot of it,
# and will be saved as a PNG file.
# The file will be located at
#   $HOME/Pictures/Screenshots/YEAR-MONTH/screenshot_DATE.png

grimblast --freeze copy area || exit
DIR=$HOME/Pictures/Screenshots/$(date +%Y-%m)
NAME=$(date +"%Y-%m-%d_%H-%M-%S")
mkdir -p "$DIR"
wl-paste --type image/png >"$DIR/screenshot_$NAME.png"
notify-send "Screenshot saved to $DIR/$NAME.png"
